apiVersion: v1
kind: Service
metadata:
  name: msa-member-service
spec:
  ports:
    - name: "8080"
      port: 8082
      targetPort: 8080
      nodePort: 30001
  selector:
    app: msa-member
  type: NodePort