apiVersion: apps/v1
kind: Deployment
metadata:
  name: msa-member-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msa-member
  template:
    metadata:
      labels:
        app: msa-member
    spec:
      containers:
        - name: msa-member
          image: ddarahakit/msa-member:0.1
          command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          env:
            - name: DATE
              value: 'DATE_STRING'
      imagePullSecrets:
        - name: my-secret